name: 📰 Collect Daily News

on:
  schedule:
    - cron: "0 5 * * *"   # каждый день в 05:00 UTC (06:00 по Белграду)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  collect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Collect and analyze news
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          REPORT_TELEGRAM_TOKEN: ${{ secrets.REPORT_TELEGRAM_TOKEN }}
          TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT }}
        run: |
          python main.py --collect-only

      - name: Commit updated selected.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            
            # Откатываем любые незакоммиченные изменения (чистая копия репо)
            git reset --hard
            git clean -fd
            
            # Подтягиваем main без конфликтов
            git fetch origin main
            git checkout main
            git pull origin main
            
            # Добавляем обновлённый файл
            git add -f data/selected.json
            
            # Проверяем, есть ли реальные изменения
            if git diff --cached --quiet; then
              echo "No changes in selected.json — skipping commit"
            else
              git commit -m "update daily selected.json [skip ci]"
              git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
              echo "✅ selected.json pushed successfully"
            fi