name: 📢 Post IT News (Half)

on:
  schedule:
    - cron: "0 6 * * *"   # первая половина утром (07:00 по Белграду)
    - cron: "0 12 * * *"  # вторая половина днём (13:00 по Белграду)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Post half of the news
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          REPORT_TELEGRAM_TOKEN: ${{ secrets.REPORT_TELEGRAM_TOKEN }}
          TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT }}
        run: |
          python main.py --half-post

      - name: Commit and push updated sent log (optional)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Полная очистка для избежания unstaged изменений
          git reset --hard
          git clean -fd

          git fetch origin main
          git checkout main
          git pull origin main

          # Если в будущем появится лог (например sent_news.json)
          if [ -f "data/sent_news.json" ]; then
            git add -f data/sent_news.json
          fi

          if git diff --cached --quiet; then
            echo "No changes to commit — skipping push"
          else
            git commit -m "update sent log [skip ci]"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
            echo "✅ Sent log pushed successfully"
          fi
